name: Deploy CDK Stack

on: 
  push:
    branchs: [main]
  

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Stack Dependencies
        run: 'sudo npm ci'
      
      - name: Install NPM
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install CDK CLI
        run: 'sudo npm install -g aws-cdk'
      
      - name: CDK Synth
        run: 'cdk synth'

      - name: Run CDK Bootstrap
        run: 'cdk bootstrap aws://415023725722/us-east-1'

      - name: CDK Deploy
        run: 'cdk deploy --require-approval never'
